#!/bin/bash 
#SBATCH -n 1 #Request 4 tasks (cores)
#SBATCH --cpus-per-task=8
#SBATCH -C centos7
#SBATCH -N 1 #Request 1 node
#SBATCH -t 0-06:00 #Request runtime of 30 minutes
#SBATCH -p sched_mit_hill,newnodes,sched_any #Run on sched_engaging_default partition
#SBATCH --mem-per-cpu=4000 #Request 4G of memory per CPU
#SBATCH -o output_%j.txt #redirect output to output_JOBID.txt
#SBATCH -e error_%j.txt #redirect errors to error_JOBID.txt
#SBATCH --mail-type=END #Mail when job starts and ends
#SBATCH --mail-user=jzung@mit.edu #email recipient
#SBATCH --array=31-35

cd /home/jzung/transversefol
echo "starting $SLURM_ARRAY_TASK_ID"
JULIA_NUM_THREADS=8 /home/jzung/.juliaup/bin/julia -e "include(\"script.jl\"); runjob($SLURM_ARRAY_TASK_ID)" > "output_$SLURM_ARRAY_TASK_ID.txt"
